<Project Sdk="Microsoft.NET.Sdk.Worker">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>dotnet-AHNiRSE-81600ebb-42a3-4e77-9062-754b1c0f57ca</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Storage.Blobs" Version="12.*" />
		<PackageReference Include="MiniExcel" Version="1.44.1" />
		<PackageReference Include="Cronos" Version="0.8.*" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
		<PackageReference Include="Npgsql" Version="8.*" />
		<PackageReference Include="prometheus-net" Version="8.*" />
		<PackageReference Include="prometheus-net.AspNetCore" Version="8.*" />
	</ItemGroup>
</Project>